import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';
import { brandColors, stateColors, blackColors, greyColors, blueColors } from '@/constants/Colors';

export const THEME = {
  light: {
    background: '#F7FBFE',
    foreground: 'hsl(0 0% 3.9%)',
    card: 'hsl(0 0% 100%)',
    cardForeground: 'hsl(0 0% 3.9%)',
    popover: 'hsl(0 0% 100%)',
    popoverForeground: 'hsl(0 0% 3.9%)',
    primary: brandColors.primary,
    primaryForeground: blackColors.white,
    secondary: brandColors.secondary,
    secondaryForeground: blackColors.white,
    muted: greyColors.gray6,
    mutedForeground: greyColors.gray3,
    accent: greyColors.gray6,
    accentForeground: 'hsl(0 0% 9%)',
    destructive: stateColors.error,
    border: greyColors.gray6,
    input: greyColors.gray6,
    ring: greyColors.gray3,
    radius: '0.625rem',
    // State colors
    info: stateColors.info,
    success: stateColors.success,
    warning: stateColors.warning,
    error: stateColors.error,
    orange: stateColors.orange,
    // Black & White
    black1: blackColors.black1,
    black2: blackColors.black2,
    black3: blackColors.black3,
    white: blackColors.white,
    // Grey scale
    gray1: greyColors.gray1,
    gray2: greyColors.gray2,
    gray3: greyColors.gray3,
    gray4: greyColors.gray4,
    gray5: greyColors.gray5,
    gray6: greyColors.gray6,
    // Blue colors
    blueLight: blueColors.light.base,
    blueLightHover: blueColors.light.hover,
    blueLightActive: blueColors.light.active,
    blueNormal: blueColors.normal.base,
    blueNormalHover: blueColors.normal.hover,
    blueNormalActive: blueColors.normal.active,
    blueDark: blueColors.dark.base,
    blueDarkHover: blueColors.dark.hover,
    blueDarkActive: blueColors.dark.active,
    blueDarker: blueColors.darker.base,
    chart1: 'hsl(12 76% 61%)',
    chart2: 'hsl(173 58% 39%)',
    chart3: 'hsl(197 37% 24%)',
    chart4: 'hsl(43 74% 66%)',
    chart5: 'hsl(27 87% 67%)',
  },
  dark: {
    background: blackColors.black2,
    foreground: blackColors.white,
    card: blackColors.black3,
    cardForeground: blackColors.white,
    popover: blackColors.black3,
    popoverForeground: blackColors.white,
    primary: brandColors.primary,
    primaryForeground: blackColors.white,
    secondary: brandColors.secondary,
    secondaryForeground: blackColors.white,
    muted: greyColors.gray2,
    mutedForeground: greyColors.gray4,
    accent: greyColors.gray2,
    accentForeground: blackColors.white,
    destructive: stateColors.error,
    border: greyColors.gray2,
    input: greyColors.gray2,
    ring: greyColors.gray4,
    radius: '0.625rem',
    // State colors
    info: stateColors.info,
    success: stateColors.success,
    warning: stateColors.warning,
    error: stateColors.error,
    orange: stateColors.orange,
    // Black & White
    black1: blackColors.black1,
    black2: blackColors.black2,
    black3: blackColors.black3,
    white: blackColors.white,
    // Grey scale
    gray1: greyColors.gray1,
    gray2: greyColors.gray2,
    gray3: greyColors.gray3,
    gray4: greyColors.gray4,
    gray5: greyColors.gray5,
    gray6: greyColors.gray6,
    // Blue colors
    blueLight: blueColors.light.base,
    blueLightHover: blueColors.light.hover,
    blueLightActive: blueColors.light.active,
    blueNormal: blueColors.normal.base,
    blueNormalHover: blueColors.normal.hover,
    blueNormalActive: blueColors.normal.active,
    blueDark: blueColors.dark.base,
    blueDarkHover: blueColors.dark.hover,
    blueDarkActive: blueColors.dark.active,
    blueDarker: blueColors.darker.base,
    chart1: 'hsl(220 70% 50%)',
    chart2: 'hsl(160 60% 45%)',
    chart3: 'hsl(30 80% 55%)',
    chart4: 'hsl(280 65% 60%)',
    chart5: 'hsl(340 75% 55%)',
  },
};
 
export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};